### PR TITLE
Update maintainer in setup.py

### PR DESCRIPTION
**Pull request by AdamRJensen**
- ~~[ ] Adds description and name entries in the appropriate "what's new" file 
      in [`docs/whatsnew`](https://github.com/pvlib/pvanalytics/tree/main/docs/whatsnew) 
      for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` 
      or this Pull Request with `` :pull:`num` ``. Includes contributor name 
      and/or GitHub username (link with `` :ghuser:`user` ``).~~
- [x] Pull request is nearly complete and ready for detailed review.
- [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

The current maintainer information in the setup.py file is outdated. The PR proposes a convention similar to what is being done for pvlib-python.

### CODE REVIEW

**Comment by cwhanse** [comment]
This is a reminder (to me) that we need to update the copyright statement.

**Comment by AdamRJensen** [comment]
Any preference for ``AUTHOR`` vs. ``MAINTAINER``?

**Comment by kandersolar** [comment]
Mild preference for AUTHOR, I think, for consistency with pvlib-python and after reading the descriptions here: https://packaging.python.org/en/latest/specifications/core-metadata/

**Comment by cwhanse** [comment]
I'd go with 

`AUTHOR=pvanalytics Contributors`

anticipating that copyright will be the same.

**Comment by cwhanse** [comment]
> LGTM.
> 
> @cwhanse should we also change the copyright statement?

We need to do some paperwork. I'd leave the copyright as is for now.

**Pull request merged**
