### PR TITLE
Update LICENSE per NREL legal review

### PR DESCRIPTION
**Pull request by cdeline**
~~Closes #xxx~~
~~Added tests to cover all new or modified code.~~
~~Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings.~~
~~Added new API functions to `docs/api.rst`.~~
~~Non-API functions clearly documented with docstrings or comments as necessary.~~
~~Adds description and name entries in the appropriate "what's new" file 
      in [`docs/whatsnew`](https://github.com/pvlib/pvanalytics/tree/main/docs/whatsnew) 
      for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` 
      or this Pull Request with `` :pull:`num` ``. Includes contributor name 
      and/or GitHub username (link with `` :ghuser:`user` ``).~~
- [x] Pull request is nearly complete and ready for detailed review.
- [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

NREL copyright review of new code contributions found that the license in pvanalytics needs to be updated.  Namely: pvlib isn't a legal entity and can't be named as a copyright holder.  The following language update was suggested which assigns copyright to NREL and Sandia.  Please contact angela.hupp@nrel.gov for the legal details.  I've asked whether we can use a similar format to pvlib-python which assigns copyright to 'pvanalytics contributors'.  That may be a possible alternative to this language.  

Copyright (c) 2020, 2022 Alliance for Sustainable Energy, LLC and National Technology and Engineering Solutions of Sandia, LLC

Thanks!
-Chris

### CODE REVIEW

**Comment by cwhanse** [comment]
Thanks @cdeline this has been on my list of things to get to for some time. I'll talk to our IP people. They may prefer the "pvanalytics contributors" language., since 3 of 6 contributors are outside of either NREL or Sandia.

**Comment by AdamRJensen** [comment]
I have plans to make several contributions but this new copyright is a serious discouragement and makes me reconsider.

If you want more non-national lab contributors then I strongly support "pvanalytics contributors" as suggested by Cliff (which also has the benefit of not becoming outdated).

**Comment by cdeline** [comment]
OK, great.  I also prefer  `PVAnalytics contributors`, as it is more flexible than enumerating each individual contributor in the license.  I'll let our copyright people know.

**Comment by cwhanse** [comment]
@cdeline I have the paperwork on my desk to file with the original sponsor office, to get their approval of a copyright. I will contact your lab's person so that NREL's interests are also represented.

And FYI, on my todo list: get a logo for this project. Stay tuned...

**Comment by cwhanse** [comment]
@cdeline NREL and Sandia lawyers are insisting on "Copyright © 2020, 2022 Alliance for Sustainable Energy, LLC and National Technology & Engineering Solutions of Sandia, LLC" They insist on this text because "pvanalytics Contributors" isn't a legal entity. It's old-think about copyright for open-source code, IMO. But it's necessary for now.

@AdamRJensen they also agree that we will add "and Contributors" or similar when a Contributor requests it.

**Comment by cdeline** [comment]
@cwhanse - Thanks for engaging with the legal folks and getting their approvals.  I've reverted back to the original Copyright 2020,2022 language.  Once we get additional contributors on a new release we can add the "and Contributors" language.  this will keep the lawyers happy for the initial release of the software.  Feel free to merge this when you're ready.

**Comment by cwhanse** [comment]
@cdeline can you merge the current pvanalytics/main into this? There's a fix there to the RTD build.

**Pull request merged**
