### PR TITLE
Example organizer

### LINKED ISSUE #154: Organize examples by topic or pvanalytics code module.
@kperrynrel you've done such a good job that we need subheadings for the examples :)

### PR DESCRIPTION
**Pull request by kperrynrel**
## Description

*Thank you for your contribution! Please provide a brief description of the problem and the proposed solution or new feature (if not already fully described in a linked issue)*

Added associated README's and split up the examples by module in the example gallery to make things more organized.

## Checklist

The following items must be addressed before the code can be merged. 
Please don't hesitate to ask for help if you are unsure of how to accomplish any of the items. 
*You are free to remove any checklist items that do not apply or add additional items that are 
not on this list*

- [x] Closes #154 
- [x] Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings
- [x] Adds description and name entries in the appropriate "what's new" file 
      in [`docs/whatsnew`](https://github.com/pvlib/pvanalytics/tree/master/docs/whatsnew) 
      for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` 
      or this Pull Request with `` :pull:`num` ``. Includes contributor name 
      and/or GitHub username (link with `` :ghuser:`user` ``).
- [x] Non-API functions clearly documented with docstrings or comments as necessary
- [x] Pull request is nearly complete and ready for detailed review

### CODE REVIEW

**Comment by kperrynrel** [comment]
@kanderso-nrel I took a stab at organizing the example gallery here. Take a look and let me know what you think

**Review by kanderso-nrel — APPROVED** [review]
Looks great!  It might be nice to combine the various lonely `features` sections (clear-sky, clipping, etc) into a single merged section, but I'm also fine with merging as is.

FYI it is possible to specify the ordering of gallery sections: https://sphinx-gallery.github.io/stable/configuration.html#sorting-gallery-subsections.  Not saying it needs to be done in this PR.

**Comment by kanderso-nrel** [comment]
> do you know why the headings appears recursively under System?

I don't see anything matching this description.  Here's how the landing page looks for me (in an "expand" item because the image is very tall):

<details>
  <summary>Click to expand!</summary>

image

</details>

Also @kperrynrel I just noticed that a copy of the `interpolated-periods.py` example accidentally made it into the Outliers section.

**Comment by cwhanse** [comment]
In the navigation panel on the left side

**Comment by kanderso-nrel** [comment]
Oh right.  It's a change in the latest `sphinx-gallery` that I don't fully understand, but it's fixed for me locally by deleting the `System` folder (it's empty anyway) and adding this to the `sphinx_gallery_conf` dict in `conf.py`:

```python
    # https://github.com/sphinx-gallery/sphinx-gallery/pull/944
    'nested_sections': False,
```

**Comment by kperrynrel** [comment]
Using @kanderso-nrel 's recommendations I was able to get the example gallery dropdown to remove the 'system' issues: 
image

Also removed the interpolated data example from the outliers folder in https://github.com/pvlib/pvanalytics/pull/155/commits/3705b105cfc95aca3f051653e5dfce9ea9b16eae

**Review by cwhanse — APPROVED** [review]
Enthusiastically approve

**Comment by kperrynrel** [comment]
Thanks for reviewing @cwhanse and @kanderso-nrel! I'm going to go ahead and squash and merge

**Pull request merged**
