### PR TITLE
v0.1.1 Release

### LINKED ISSUE #130: Release ahead of PVRW?
@cdeline suggested cutting a (possibly beta) release ahead of PVRW next week to have something nice to reference during the workshop.  Here's the current whatsnew: https://github.com/pvlib/pvanalytics/blob/master/docs/whatsnew/0.1.1.rst

As an aside, @kperrynrel and @MichaelHopwood are missing from the contributors list in that file and need to be added.

Not sure how close #111 is.  #124 and #127 both seem pretty close but IMHO aren't necessarily required since we're a bit short on time.  I would like to see #129 (or some reduced version of it) get merged before the next release for the scipy fix it contains.  I'm not seeing any issues that I think are necessarily crucial to get into the next release, though #117 would be nice to have.  

I think we don't have any breaking changes yet, so this could be v0.1.1 or v0.1.1-beta.0.  Should we aim for a release by the end of this week?

### PR DESCRIPTION
**Pull request by kanderso-nrel**
## Description

Cleaning up the whatsnew and a few other docs things.  I left it as 0.1.1, but wouldn't object to 0.2.0 if others prefer that.  

## Checklist

The following items must be addressed before the code can be merged. 
Please don't hesitate to ask for help if you are unsure of how to accomplish any of the items. 
*You are free to remove any checklist items that do not apply or add additional items that are 
not on this list*

- [x] Closes #130
- ~Added new API functions to `docs/api.rst`~
- ~Clearly documented all new API functions with [PEP257](https://www.python.org/dev/peps/pep-0257/) and [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings~
- [x] Adds description and name entries in the appropriate "what's new" file 
      in [`docs/whatsnew`](https://github.com/pvlib/pvanalytics/tree/master/docs/whatsnew) 
      for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` 
      or this Pull Request with `` :pull:`num` ``. Includes contributor name 
      and/or GitHub username (link with `` :ghuser:`user` ``).
- ~Non-API functions clearly documented with docstrings or comments as necessary~
- ~Added tests to cover all new or modified code~
- [x] Pull request is nearly complete and ready for detailed review

### CODE REVIEW

**Review by cwhanse — APPROVED** [review]
@wfvining do you want to take a look?

**Comment by kanderso-nrel** [comment]
I don't mind not releasing this today, but let's be sure not to merge this without making sure the release date in the whatsnew file is correct :)

**Comment by cwhanse** [comment]
@kanderso-nrel the only question is about moving the requirements.txt file for the doc build, because I don't understand how that works. It's clear it does work, but perhaps could you briefly explain why it moved?

**Comment by kanderso-nrel** [comment]
Not moved but deleted entirely.  It only contained a single dependency specifier (`sphinx==2.2.0`).  After installing that requirements file, RTD followed it up with a call to `pip install .[doc]`, which uninstalled the original version and replaces it with `sphinx == 4.3.1`.  So the `docs/requirements.txt` file had no effect on the final result and introduced a small amount of clutter and slowdown in the build for no benefit.

**Comment by cwhanse** [comment]
Thanks. Merge away and release!

**Pull request merged**
